### ISSUE TITLE
[global] var assignments don't have effect in [vb-instance] stanzas

### ISSUE THREAD

**Issue by asconix** [ployground/bsdploy#100]
Setting global variables in `[global]` section of `ploy.conf` like

    [global]
    vm-ostype = FreeBSD_64
    vm-memory = 3072

... has no effect on `[vb-instance]` stanzas. All VirtualBox instances are created using the default memory size, not the custom one from `[global]`.

Any ideas how to change it?

Cheerio,
Chris

**Comment by fschulze** [comment]
Those variables are only looked up on the instance config. You can use macro expansion, but you explicitly have to use the macro, it won't work automatically for new instances. See "Macro expansion" in https://pypi.python.org/pypi/ploy.

**Comment by asconix** [comment]
Right, that makes sense :) Works fine.
