### ISSUE TITLE
digitalocean fabfile needs an update for FreeBSD 11

### ISSUE THREAD

**Issue by igalic** [ployground/bsdploy#101]
```python
sudo("""cat /etc/rc.digitalocean.d/droplet.conf > /etc/rc.conf""")
```

this file is gone in the Fbsd11 image, but that's okay, cuz the default rc.conf is already pretty much ready.

```python
 sudo("""echo 'PermitRootLogin without-password' > /etc/ssh/sshd_config""")
```

This is now the default, however, there's also an  `Match` clause at the end which rejects the `root` login altogether. And, in addition to that, the `root` account is also locked out… so we'll need to snip off the last two lines, and then:

```python
 sudo("""pw unlock root""")
```

This is gone in the new revision:

```python
   # clean up DO cloudinit leftovers
    run("rm /etc/rc.d/digitalocean")
    run("rm -r /etc/rc.digitalocean.d")
    run("rm -r /usr/local/bsd-cloudinit/")
    run("pkg remove -y avahi-autoipd")
```

**Comment by fschulze** [comment]
Can you take a look at #105?

**Comment by tomster** [comment]
damn, i had to figure this out myself, because my sieve of a brain didn't remember reading this PR... doh! thanks a bunch @igalic for contributing this!

**Comment by fschulze** [comment]
Looks like this was fixed.
