### ISSUE TITLE
Duplicate installation of Python 2

### ISSUE THREAD

**Issue by fschulze** [ployground/bsdploy#104]
In 2.2.0 the base flavour gained installation of ``python2``, but this is already done in the startup script ``startup-ansible-jail.sh``, maybe the only issue was that it installs ``python2.7`` instead of ``python2``, which doesn't add the ``python2`` alias?

**Comment by tomster** [comment]
that was an oversight. not sure which is the 'proper' place to do it, but basically, the sooner the better. i haven't used the `python2` alias so far, so it shouldn't be an issue.

**Comment by fschulze** [comment]
I would say the startup script is the proper place, because then it can still be overwritten per jail if wanted (I do that in one case).

**Comment by fschulze** [comment]
Fixed in 2.3.0
