### ISSUE TITLE
rsa1: unknown or unsupported key type

### ISSUE THREAD

**Issue by s4ms0n** [ployground/bsdploy#107]
getting the:
unknown or unsupported key type
in line 97:
('ssh_host_key', '-t rsa1 -b 1024'),
of the bootstrap_utils.py file.
Any reason for the ssh key to be rsa1 and not just rsa?
Thanks

**Comment by fschulze** [comment]
I guess newer versions of ssh finally stopped supporting such old keys, I guess we should as well. Can you try to find out what version of ssh (or OpenSSH) you have?

**Comment by s4ms0n** [comment]
OpenSSH_7.3p1-hpn14v11, OpenSSL 1.0.2k  26 Jan 2017 on client and
OpenSSH_7.2p2, OpenSSL 1.0.2j-freebsd  26 Sep 2016 on server (FreeBSD 11.0)
neither supports rsa1.
i would also suggest dropping the support for rsa1, or at least make it configurable.

**Comment by tomster** [comment]
I simply tried changing `rsa1` to `rsa` as suggested by @s4ms0n and while i was at it i increased the key size to a somewhat more modern (but still moderate) value of `2048`.

This has worked locally for me, i'll let @fschulze review first and do the merge, though

**Comment by s4ms0n** [comment]
works for me, closing the issue
