### ISSUE TITLE
[idea] Add a section for ovh in documentation

### ISSUE THREAD

**Issue by oscarmlage** [ployground/bsdploy#45]
As Hetzner, OVH is one of the most used providers (in Europe iirc), it would be nice to see an example like the Hetzner one.

**Comment by tomster** [comment]
@oscarmlage actually, i'd love to expand the list of supported ISPs. do you have an account with them? if you're still(!) interested, i could offer pair on bootstrapping a host remotely with you and add a chapter to the docs as a result.

**Comment by tomster** [comment]
since nobody seems to be stepping forward with OVH i'm closing this.

@oscarmlage feel free to re-open if/when you have more specific details or needs.

**Comment by oscarmlage** [comment]
Hey, sorry to being so late in this reply. I've actually an empty OVH machine (I was using it til this month), I've renovate it one month more with the idea of offering it for test purposes.
