### ISSUE TITLE
ploy configure demo_jail: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by a-sk** [ployground/bsdploy#49]
Hello.
I was going through the [quick start guide](http://docs.bsdploy.net/en/latest/quickstart.html) step by step and I encountered ansible related error. 
When I'm trying to configure (ploy configure) ansible complains that it can't connect to host by it's name `jailhost`, so I put jailhost to my hosts file and it worked fine until I tried to provision a jail.
As far as I understand, jails do not expose ssh and `ploy ssh` connects through the jailhost, using `ssh -W` and I do not know how to tell ansible to do the same.
### System info

Mac os 10.10.1

```
$ ploy -v
bsdploy 1.3 (/usr/local/lib/python2.7/site-packages)
ploy 1.0.2 (/usr/local/lib/python2.7/site-packages)
ploy-ansible 1.2.0 (/usr/local/lib/python2.7/site-packages)
ploy-ezjail 1.1.0 (/usr/local/lib/python2.7/site-packages)
ploy-fabric 1.1.0 (/usr/local/lib/python2.7/site-packages)
ploy-virtualbox 1.0.0 (/usr/local/lib/python2.7/site-packages)
```
### Ploy output

```
$ ploy configure demo_jail

PLAY [jailhost-demo_jail] *****************************************************

GATHERING FACTS ***************************************************************
fatal: [jailhost-demo_jail] => {'msg': 'FAILED: [Errno 8] nodename nor servname provided, or not known', 'failed': True}

TASK: [install nginx] *********************************************************
FATAL: no hosts matched or all hosts have already failed -- aborting
```

**Comment by JMStudiosJoe** [comment]
Has this been updated?

**Comment by gretel** [comment]
:+1:

**Comment by tomster** [comment]
@JMStudiosJoe & @gretel yes, this has been resolved since. bsdploy currently works with all versions of ansible >= 1.8

**Comment by gretel** [comment]
@tomster cool, thanks. i suggest having a comment in relation to the closing to prevent confusion. regards :shaved_ice:
