### ISSUE TITLE
ploy configure gives Traceback

### ISSUE THREAD

**Issue by dlangille** [ployground/bsdploy#60]
I am trying to get my first jail host configured.  I'm failing.

This succeeds:

<pre>
# ploy ssh tallboy
</pre>

This fails:

<pre>
# ploy configure tallboy-jailhost
Traceback (most recent call last):
  File "/usr/local/bin/ploy", line 9, in <module>
    load_entry_point('ploy==1.0.3', 'console_scripts', 'ploy')()
  File "/usr/local/lib/python2.7/site-packages/ploy/__init__.py", line 540, in ploy
    return ctrl(argv)
  File "/usr/local/lib/python2.7/site-packages/ploy/__init__.py", line 532, in __call__
    args.func(sub_argv, args.func.__doc__)
  File "/usr/local/lib/python2.7/site-packages/ploy_ansible/__init__.py", line 623, in __call__
    extra_vars = parse_extra_vars(args.extra_vars)
  File "/usr/local/lib/python2.7/site-packages/ploy_ansible/__init__.py", line 262, in parse_extra_vars
    inject_ansible_paths()
  File "/usr/local/lib/python2.7/site-packages/ploy_ansible/__init__.py", line 41, in inject_ansible_paths
    C.DEFAULT_MODULE_PATH = pathsep.join([pathsep.join(extra_library), C.DEFAULT_MODULE_PATH])
TypeError: sequence item 1: expected string, NoneType found
</pre>

Details of configuration:

<pre>
# cat etc/ploy.conf
[plain-instance:tallboy]
host        = tallboy.example.org
user        = dvl
fingerprint = REDACTED

[ez-master:tallboy-jailhost]
instance = tallboy
roles    = jails_host
</pre>

remote host is FreeBSD 10.1, freshly installed today.

localhost is FreeBSD 9.3 with:

<pre>
bsdploy-1.3
py27-ploy-1.0.3
py27-ploy_ansible-1.2.1
py27-ploy_ec2-1.1.0
py27-ploy_ezjail-1.1.0
py27-ploy_fabric-1.1.0
</pre>

**Comment by tomster** [comment]
FYI i was able to reproduce this inside a FreeBSD 9.3 jail - both by using the ```pkg``` based versions, as well as ```pip``` installed inside a virtualenv.

i've also verified that this does *not* happen when using identical versions inside a virtualenv on mac os x.

@fschulze : i guess we will need to filter out ```None``` values here as a workaround

**Comment by tomster** [comment]
@dlangille i've created a workaround in https://github.com/ployground/ploy_ansible/pull/12

if you are able to install ploy_ansible from that branch you should be able to continue your setup for now.

HTH

**Comment by fschulze** [comment]
I replied on Twitter already, I'm pretty sure it's ansible > 1.7

**Comment by tomster** [comment]
ansible is definitely at 1.7.2 in the virtualenv i reproduced this in

**Comment by tomster** [comment]
ok, the pkg installs a global ansible 1.8.x which causes this (and other) errors.

@dlangille the workaround i mentioned above is likely to leave other side-effects uncovered.

the only reliable way for you to continue at the moment is to remove the bsdploy pkg and install bsdploy into a virtualenv as described here http://docs.bsdploy.net/en/latest/installation.html#installing-from-pypi

**Comment by koobs** [comment]
@dlangille Alternatively, install ansible < 1.8 and use the pkg/port :)

**Comment by tomster** [comment]
this has been fixed in https://github.com/ployground/ploy_ansible/releases/tag/1.2.2 - a pkg update is still pending but besides that i think this issue can be regarded as closed.
