### ISSUE TITLE
ezjail and /etc/jail.conf

### ISSUE THREAD

**Issue by abelbabel** [ployground/bsdploy#61]
As `ezjail` still does not support new `/etc/jail.conf` style and the day comes closer where FreeBSD will drop support for legacy rc-jail-conf what is the solution for the not so far future?

**Comment by fschulze** [comment]
Getting @tomster to poke erdgeist as often as necessary to get him to support the new style :smiley: 

Another way would be creating a substitute for ploy_ezjail which works directly with FreeBSD. I understand what ezjail does quite a bit better now and this might be the way forward. Haven't decided yet.

**Comment by abelbabel** [comment]
Speaking of substitutes [iocage](https://github.com/pannon/iocage/) might be an interresting candidate, too.

**Comment by tomster** [comment]
agreed, iocage is an interesting candidate. but currently we're still pretty much invested in ezjail. i'm actually nudging its author (we share an office) to release 3.4.2 with some fixes.

eventually, ezjail will adjust to the new jail.conf style but it's a tricky issue in itself - basically the whole jail config situation is more or less in limbo on FreeBSD-CURRENT now, from what i've learnt.

bsdploy's stance is to let others deal with this until our hand is forced :-)

**Comment by tehfink** [comment]
+1 for iocage! It would be nice to be agnostic towards the jail-management utility, yes?

**Comment by mzs114** [comment]
I would suggest glancing qjail once, its basically ezjail plus some enhancements. I am linking it.

**Comment by tomster** [comment]
@mzs114 i'm familiar with the history of qjail and i can assure you that (unlike iocage) it is probably the last piece of software that i would consider integrating into bsdploy.

**Comment by mzs114** [comment]
@tomster is there such a reason to not use qjail?  :-?

I did not use iocage as it requires ZFS and some of my nodes have UFS. The other one I used was CBSD for multinode management of jails https://www.bsdstore.ru/en/about.html
In fact, I was wondering whether we can make bsdploy work with CBSD.

**Comment by fschulze** [comment]
I'm actually thinking about not using any wrapper at all and just do a ploy_jail.

**Comment by tomster** [comment]
@mzs114 i won't go into any details here re: qjail, but if you're really interested check the archives of the FreeBSD jail mailing list. it's not pretty, though :(
