### ISSUE TITLE
How to bootstrap with another private key?

### ISSUE THREAD

**Issue by smiklosovic** [ployground/bsdploy#88]
I have the following problem.

I am doing ploy bootstrap myinstance and it notifies me that in bootstrap_files there is not any authorized_keys file and it asks if it is ok to add there public key from ~/.ssh.

If I answer yes, this file will be copied over mfsbsd and bootstrap process will use it. It gets passwordless access because bootstrap uses id_dsa / id_dsa files in ~/.ssh while authenticating.

My scenario is that after bootstrapping of that whole environment, I just pack that machine to Vagrant box and I am using that box with vagrant up ...

The thing is that I can not do vagrant ssh into it by default, I have to point vagrant to my identity file (id_dsa) in ~/.ssh so vagrant can pick it up. If I did not set it, it would use some default insecure key and that key is obviously not in authorized_keys so the access will be refused.

Now the problem is that I would have to put my private key to source control which is not obviously what I want so I was thinking that I just use pregenerated keypair and I put public key to authorized_keys in bootstrap_files.

But when I do that, I am not able to bootstrap it anymore because bootstrap does not use that corresponding private key so it asks for password but I can not provide any.

**Comment by smiklosovic** [comment]
One possible workaround is to skip this whole process in bootstrapping stage and in configure stage, I would just invoke ansible playbook with task which would add vagrant's insecure key to authorized_keys hence once all is configured and boxed and I do vagrant ssh, it detects I am using insecure key and it adds some randomly generated dynamically to authorized_keys file.

**Comment by tomster** [comment]
well, the 'official' way would be to include your particular private key in your bootstrap files. we do this for most projects, actually and host the private keys using `ploy vault` (see http://ploy.readthedocs.org/en/latest/ploy_ansible/README.html#commands)

does this help you?

note to self: we should add a section on using the vault in the bsdploy documentation...

**Comment by smiklosovic** [comment]
I did it as I wrote in my second comment. I am running an Ansible playbook which adds the insecure Vagrant ssh key in the `configure` phase. This works nicely, as expected and to my satisfaction.

**Comment by tomster** [comment]
great :)
